# Generated by Django 3.2.14 on 2022-07-13 14:30

import cei.entity.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=cei.entity.models.now, editable=False)),
            ],
        ),
    ]
